# Generated by Django 5.0.4 on 2024-04-06 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomsApp', '0002_jihoz'),
        ('studentsApp', '0002_remove_student_fakultet_remove_student_haqdor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='imtiyozli',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='joy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roomsApp.joy'),
        ),
    ]
