# Generated by Django 5.0.4 on 2024-04-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0003_student_imtiyozli_alter_student_joy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guruh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentsApp.guruh'),
        ),
    ]
