# Generated by Django 5.0.4 on 2024-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0004_alter_student_guruh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guruh',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
