# Generated by Django 5.0.3 on 2024-04-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
    ]
