# Generated by Django 5.0.4 on 2024-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_profil_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('xodim', 'xodim'), ('nazoratchi', 'nazoratchi')], max_length=50),
        ),
    ]
