# Generated by Django 5.0.3 on 2024-04-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joy',
            options={'verbose_name': 'Joy', 'verbose_name_plural': 'Joylar'},
        ),
        migrations.AlterModelOptions(
            name='xona',
            options={'verbose_name': 'Xona', 'verbose_name_plural': 'Xonalar'},
        ),
    ]
